-- @Description Tests truncate table success and failure case in function with exception
-- 
DROP TABLE IF EXISTS public.test_exception_error CASCADE;
DROP TABLE
DROP FUNCTION IF EXISTS test_plpgsql() CASCADE;
DROP FUNCTION
CREATE TABLE public.test_exception_error (a INTEGER NOT NULL);
psql:/path/sql_file:1: NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
INSERT INTO public.test_exception_error select * from generate_series(1, 100);
INSERT 0 100
-- SUCCESS case
CREATE OR REPLACE FUNCTION public.test_plpgsql() RETURNS VOID AS
$$
BEGIN
	TRUNCATE TABLE public.test_exception_error;
	INSERT INTO public.test_exception_error select * from generate_series(100, 150);
EXCEPTION WHEN OTHERS THEN
	RAISE NOTICE 'catching the exception ...';
END;
$$
LANGUAGE plpgsql;
CREATE FUNCTION
SELECT public.test_plpgsql();
 test_plpgsql 
--------------
 
(1 row)

SELECT count(*) FROM public.test_exception_error;
 count 
-------
    51
(1 row)

INSERT INTO public.test_exception_error SELECT * FROM generate_series(150, 200);
INSERT 0 51
-- FAILURE scenario
CREATE OR REPLACE FUNCTION public.test_plpgsql() RETURNS VOID AS
$$
BEGIN
	TRUNCATE TABLE public.test_exception_error;
	INSERT INTO public.test_exception_error select * from generate_series(200, 250);
	INSERT INTO public.test_exception_error(a) VALUES(NULL);
EXCEPTION WHEN OTHERS THEN
	RAISE NOTICE 'catching the exception ...';
END;
$$
LANGUAGE plpgsql;
CREATE FUNCTION
-- Raises Exception
SELECT public.test_plpgsql();
psql:/path/sql_file:1: NOTICE:  catching the exception ...
 test_plpgsql 
--------------
 
(1 row)

SELECT count(*) FROM public.test_exception_error;
 count 
-------
   102
(1 row)

INSERT INTO public.test_exception_error select * from generate_series(250, 300);
INSERT 0 51
-- FAILURE scenario
CREATE OR REPLACE FUNCTION public.test_plpgsql() RETURNS VOID AS
$$
BEGIN
	INSERT INTO public.test_exception_error select * from generate_series(300, 350);
	INSERT INTO public.test_exception_error(a) VALUES(NULL);
EXCEPTION WHEN OTHERS THEN
	BEGIN
		TRUNCATE TABLE public.test_exception_error;
		RAISE NOTICE 'catching the exception ...';
	END;
END;
$$
LANGUAGE plpgsql;
CREATE FUNCTION
-- Raises Exception
SELECT public.test_plpgsql();
psql:/path/sql_file:1: NOTICE:  catching the exception ...
 test_plpgsql 
--------------
 
(1 row)

SELECT count(*) FROM public.test_exception_error;
 count 
-------
     0
(1 row)

INSERT INTO public.test_exception_error select * from generate_series(350, 400);
INSERT 0 51
SELECT count(*) FROM public.test_exception_error;
 count 
-------
    51
(1 row)

